services:
  frontend:
    build: ./services/frontend
    ports:
      - "3000:3000"
  data-service:
    build: ./services/data-service
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    volumes:
      - ./services/data-service:/app
      - /app/node_modules
  simulation-engine:
    build: ./services/simulation-engine
    ports:
      - "3002:3002"
  timescaledb:
    build: ./infra/database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

volumes:
  timescaledb-data:
